/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.promptzal.frontend;

import com.mycompany.promptzal.Token;
import com.mycompany.promptzal.Tokenizador;
import java.io.File;
import java.nio.file.Files;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrk-ema
 */
public class Contenedor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Contenedor.class.getName());

    /**
     * Creates new form Contenedor
     */
    public Contenedor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public String getTextoEditor() {
        return textAreaEditor.getText();
    }

    public void setTextoEditor(String texto) {
        textAreaEditor.setText(texto);
    }

    public void mostrarTokens(List<Token> tokens) {
        DefaultTableModel modelo = (DefaultTableModel) tablaTokens.getModel();
        modelo.setRowCount(0);
        for (Token t : tokens) {
            String lexema = t.getLexema();
            if ("Literal cadena".equals(t.getTipo()) && lexema.startsWith("\"") && lexema.endsWith("\"")) {
                lexema = lexema.substring(1, lexema.length() - 1);
            }
            modelo.addRow(new Object[]{lexema, t.getTipo(), t.getFila(), t.getColumna()});
        }
    }

    public void mostrarErrores(List<Token> errores) {
        DefaultTableModel modelo = (DefaultTableModel) tablaErrores.getModel();
        modelo.setRowCount(0);
        if (errores.isEmpty()) {
            modelo.addRow(new Object[]{"Ninguno", "No se encontraron errores lexicos", "-", "-"});
        } else {
            for (Token e : errores) {
                modelo.addRow(new Object[]{e.getLexema(), e.getTipo(), e.getFila(), e.getColumna()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollEditor = new javax.swing.JScrollPane();
        textAreaEditor = new javax.swing.JTextArea();
        btnCargar = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        tabbedResultados = new javax.swing.JTabbedPane();
        scrollTokens = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        scrollErrores = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PromptZal - Analizador Lexico (Proyecto 1)");

        textAreaEditor.setColumns(20);
        textAreaEditor.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textAreaEditor.setRows(5);
        textAreaEditor.setText("@modelo \"claude-sonnet-4-6\"\n@rol \"analista financiero\"\nAGENTE analista {\n    contexto = \"Eres un analista de finanzas\"\n    variable ventas = CARGAR(\"ventas.csv\")\n    PREGUNTAR \"Cuales fueron las 3 tendencias principales?\" SOBRE ventas -> reporte\n}\n\nEJECUTAR analista\nEXPORTAR reporte\n");
        scrollEditor.setViewportView(textAreaEditor);

        btnCargar.setText("Cargar Codigo");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnAnalizar.setText("Analizar Codigo");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Tipo", "Fila", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTokens.setViewportView(tablaTokens);

        tabbedResultados.addTab("Tokens Reconocidos", scrollTokens);

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema / Caracter", "Tipo de Error", "Fila", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollErrores.setViewportView(tablaErrores);

        tabbedResultados.addTab("Errores Lexicos", scrollErrores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollEditor)
                    .addComponent(tabbedResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos PromptZal (.pz)", "pz"));
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = fileChooser.getSelectedFile();
                String contenido = Files.readString(archivo.toPath());
                textAreaEditor.setText(contenido);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        String contenido = textAreaEditor.getText();
        if (contenido == null || contenido.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El editor esta vacio.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Tokenizador tokenizador = new Tokenizador();
        tokenizador.analizar(contenido);
        List<Token> tokens = tokenizador.getTokens();
        List<Token> errores = tokenizador.getErrores();

        mostrarTokens(tokens);
        mostrarErrores(errores);

        JOptionPane.showMessageDialog(this,
            "Analisis completado.\n" +
            "Tokens: " + tokens.size() + "\n" +
            "Errores: " + errores.size(),
            "Resultado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAnalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JScrollPane scrollEditor;
    private javax.swing.JScrollPane scrollErrores;
    private javax.swing.JScrollPane scrollTokens;
    private javax.swing.JTabbedPane tabbedResultados;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JTable tablaTokens;
    private javax.swing.JTextArea textAreaEditor;
    // End of variables declaration//GEN-END:variables
}
