/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.promptzal.frontend;

import com.mycompany.promptzal.Token;
import com.mycompany.promptzal.Tokenizador;
import java.io.File;
import java.nio.file.Files;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mrk-ema
 */
public class Contenedor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Contenedor.class.getName());

    private Editor editorPanel;
    private Resultados resultadosPanel;

    private List<Token> ultimosTokens = new java.util.ArrayList<>();
    private List<Token> ultimosErrores = new java.util.ArrayList<>();
    private String ultimoNombreArchivo = "codigo_promptzal.pz";
    private boolean analizado = false;

    /**
     * Creates new form Contenedor
     */
    public Contenedor() {
        initComponents();

        editorPanel = new Editor();
        resultadosPanel = new Resultados();
        jSplitPane1.setLeftComponent(editorPanel);
        jSplitPane1.setRightComponent(resultadosPanel);
        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setResizeWeight(0.5);
        setSize(1100, 700);

        editorPanel.getDocumento().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                analizado = false;
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                analizado = false;
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                analizado = false;
            }
        });

        itemAbrir.addActionListener(evt -> abrirArchivo());
        itemGuardar.addActionListener(evt -> guardarArchivo());
        itemGenerarHTML.addActionListener(evt -> generarHTML());
        jMenuItem2.addActionListener(evt -> generarAFD());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemGenerarAFD = new javax.swing.JMenu();
        itemAnalizar = new javax.swing.JMenuItem();
        itemGenerarHTML = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        itemAbrir.setText("Abrir codigo");
        jMenu1.add(itemAbrir);

        itemGuardar.setText("Guardar codigo");
        jMenu1.add(itemGuardar);

        jMenuBar1.add(jMenu1);

        itemGenerarAFD.setText("Acciones");

        itemAnalizar.setText("Analizar codigo");
        itemAnalizar.addActionListener(this::itemAnalizarActionPerformed);
        itemGenerarAFD.add(itemAnalizar);

        itemGenerarHTML.setText("Generar reporte HTML");
        itemGenerarAFD.add(itemGenerarHTML);

        jMenuItem2.setText("Generar AFD");
        itemGenerarAFD.add(jMenuItem2);

        jMenuBar1.add(itemGenerarAFD);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAnalizarActionPerformed
        analizarCodigo();
    }//GEN-LAST:event_itemAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Contenedor().setVisible(true));
    }

    private void abrirArchivo() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos PromptZal (.pz)", "pz"));
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = fileChooser.getSelectedFile();
                String contenido = Files.readString(archivo.toPath());
                editorPanel.setTexto(contenido);
                ultimoNombreArchivo = archivo.getName();
                analizado = false;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void guardarArchivo() {
        String contenido = editorPanel.getTexto();
        if (contenido == null || contenido.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El editor esta vacio. No hay nada que guardar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos PromptZal (.pz)", "pz"));
        fileChooser.setSelectedFile(new File(ultimoNombreArchivo));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = fileChooser.getSelectedFile();
                String ruta = archivo.getAbsolutePath();
                if (!ruta.endsWith(".pz")) {
                    ruta += ".pz";
                    archivo = new File(ruta);
                }
                Files.writeString(archivo.toPath(), contenido);
                ultimoNombreArchivo = archivo.getName();
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void analizarCodigo() {
        String contenido = editorPanel.getTexto();
        if (contenido == null || contenido.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El editor esta vacio.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Tokenizador tokenizador = new Tokenizador();
        tokenizador.analizar(contenido);
        ultimosTokens = tokenizador.getTokens();
        ultimosErrores = tokenizador.getErrores();
        analizado = true;

        resultadosPanel.mostrarTokens(ultimosTokens);
        resultadosPanel.mostrarErrores(ultimosErrores);

        JOptionPane.showMessageDialog(this,
                "Analisis completado.\n"
                + "Tokens: " + ultimosTokens.size() + "\n"
                + "Errores: " + ultimosErrores.size(),
                "Resultado", JOptionPane.INFORMATION_MESSAGE);
    }

    private void generarHTML() {
        String contenido = editorPanel.getTexto();
        if (contenido == null || contenido.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El editor esta vacio. Escriba codigo y analicelo primero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!analizado) {
            Tokenizador tokenizador = new Tokenizador();
            tokenizador.analizar(contenido);
            ultimosTokens = tokenizador.getTokens();
            ultimosErrores = tokenizador.getErrores();
            analizado = true;
            resultadosPanel.mostrarTokens(ultimosTokens);
            resultadosPanel.mostrarErrores(ultimosErrores);
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Reporte HTML (.html)", "html"));
        String nombreHtml = ultimoNombreArchivo.endsWith(".pz") ? ultimoNombreArchivo.substring(0, ultimoNombreArchivo.length() - 3) + ".html" : "reporte_promptzal.html";
        fileChooser.setSelectedFile(new File(nombreHtml));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = fileChooser.getSelectedFile();
                String ruta = archivo.getAbsolutePath();
                if (!ruta.endsWith(".html")) {
                    ruta += ".html";
                    archivo = new File(ruta);
                }
                String html = com.mycompany.promptzal.Reportes.generarHTML(ultimosTokens, ultimosErrores, ultimoNombreArchivo);
                Files.writeString(archivo.toPath(), html);
                JOptionPane.showMessageDialog(this, "Reporte HTML generado exitosamente en:\n" + archivo.getAbsolutePath(), "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al generar el reporte HTML: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void generarAFD() {
        String contenido = editorPanel.getTexto();
        if (contenido == null || contenido.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El editor esta vacio. Escriba codigo y analicelo primero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!analizado) {
            Tokenizador tokenizador = new Tokenizador();
            tokenizador.analizar(contenido);
            ultimosTokens = tokenizador.getTokens();
            ultimosErrores = tokenizador.getErrores();
            analizado = true;
            resultadosPanel.mostrarTokens(ultimosTokens);
            resultadosPanel.mostrarErrores(ultimosErrores);
        }

        JOptionPane.showMessageDialog(this, "La generacion del AFD estara disponible pronto.",
                "Generar AFD", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemAnalizar;
    private javax.swing.JMenu itemGenerarAFD;
    private javax.swing.JMenuItem itemGenerarHTML;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
