/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.promptzal.frontend;

/**
 *
 * @author mrk-ema
 */
public class Editor extends javax.swing.JPanel {

    /**
     * Creates new form Editor_Panel
     */
    public Editor() {
        initComponents();
        textAreaEditor.setText("entero a = 10;\n"
                + "string nombre = \"PromptZal\";\n"
                + "real pi = 3.1416;\n"
                + "bool flag = true;\n"
                + "// este es un comentario de una linea\n"
                + "/* comentario\n"
                + "   de varias lineas */\n"
                + "123456 : cadena mal formada");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEditor = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        textAreaEditor.setColumns(20);
        textAreaEditor.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textAreaEditor.setRows(5);
        jScrollPane1.setViewportView(textAreaEditor);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    public String getTexto() {
        return textAreaEditor.getText();
    }

    public void setTexto(String texto) {
        textAreaEditor.setText(texto);
    }

    public javax.swing.text.Document getDocumento() {
        return textAreaEditor.getDocument();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaEditor;
    // End of variables declaration//GEN-END:variables
}
