/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.promptzal.frontend;

/**
 *
 * @author mrk-ema
 */
public class Resultados extends javax.swing.JPanel {

    /**
     * Creates new form Resultados
     */
    public Resultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestañas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lexema", "Tipo", "Fila", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaTokens);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pestañas.addTab("Tokens Reconocidos", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lexema", "Tipo de Error", "Fila", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaErrores);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pestañas.addTab("Errores Lexicos", jPanel2);

        add(pestañas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    public void mostrarTokens(java.util.List<com.mycompany.promptzal.Token> tokens) {
        javax.swing.table.DefaultTableModel m = (javax.swing.table.DefaultTableModel) tablaTokens.getModel();
        m.setRowCount(0);
        for (com.mycompany.promptzal.Token t : tokens) {
            String lexema = t.getLexema();
            if ("Literal cadena".equals(t.getTipo()) && lexema.startsWith("\"") && lexema.endsWith("\"")) {
                lexema = lexema.substring(1, lexema.length() - 1);
            }
            m.addRow(new Object[]{lexema, t.getTipo(), t.getFila(), t.getColumna()});
        }
    }

    public void mostrarErrores(java.util.List<com.mycompany.promptzal.Token> errores) {
        javax.swing.table.DefaultTableModel m = (javax.swing.table.DefaultTableModel) tablaErrores.getModel();
        m.setRowCount(0);
        if (errores.isEmpty()) {
            m.addRow(new Object[]{"Ninguno", "No se encontraron errores lexicos", "-", "-"});
        } else {
            for (com.mycompany.promptzal.Token e : errores) {
                m.addRow(new Object[]{e.getLexema(), e.getTipo(), e.getFila(), e.getColumna()});
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane pestañas;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JTable tablaTokens;
    // End of variables declaration//GEN-END:variables
}
